{
 "title": "EPAM",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "db.local mem available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter\",instance=\"db.local:9100\"}/1024/1024/1024",
     "legendFormat": "Mem free gb"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\",instance=\"db.local:9100\"}/1024/1024/1024",
     "legendFormat": "Mem total gb"
    }
   ]
  },
  {
   "title": "db.local io /dev/md0p1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_disk_io_now{job=\"node_exporter\",instance=\"db.local:9100\"}[5m])",
     "legendFormat": "Disk io total"
    },
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=\"db.local:9100\"}[5m])",
     "legendFormat": "Read-time sec total"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=\"db.local:9100\"}[5m])",
     "legendFormat": "Write-time sec total"
    }
   ]
  },
  {
   "title": "web.local CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node_exporter\",instance=\"web.local:9100\",mode=\"system\"}[5m])"
    },
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node_exporter\",instance=\"web.local:9100\",mode=\"iowait\"}[5m])"
    }
   ]
  },
  {
   "title": "router.local CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node_exporter\",instance=\"router.local:9100\",mode=\"system\"}[5m])"
    },
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node_exporter\",instance=\"router.local:9100\",mode=\"iowait\"}[5m])"
    }
   ]
  },
  {
   "title": "db.local CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node_exporter\",instance=\"db.local:9100\",mode=\"system\"}[5m])"
    },
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node_exporter\",instance=\"db.local:9100\",mode=\"iowait\"}[5m])"
    }
   ]
  }
 ]
}